import { useEffect, useRef, useState } from 'react'
import { useApp } from '../context/AppContext.jsx'
import { sendChatMessage } from '../api/apiClient.js'
import { useAsyncAction } from '../hooks/useAsyncAction.js'
import DisclaimerBanner from '../components/DisclaimerBanner.jsx'
import WhatIfPanel from '../components/WhatIfPanel.jsx'
import { RiskBadge } from '../components/ui/Badge.jsx'
import { SUGGESTED_QUESTIONS } from '../data/suggestedQuestions.js'

function newMessageId() {
  return `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`
}

export default function Chatbot() {
  const { state, dispatch } = useApp()
  const [draft, setDraft] = useState(state.chat.draft || '')
  const { run, loading, error, reset } = useAsyncAction(sendChatMessage)
  const scrollRef = useRef(null)

  const messages = state.chat.messages
  const selectedPlan = state.selectedPlan

  useEffect(() => {
    if (state.chat.draft) {
      setDraft(state.chat.draft)
      dispatch({ type: 'SET_CHAT_DRAFT', draft: '' })
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [state.chat.draft])

  useEffect(() => {
    scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: 'smooth' })
  }, [messages, loading])

  async function sendMessage(text) {
    const trimmed = text.trim()
    if (!trimmed || loading) return

    reset()
    const userMessage = { id: newMessageId(), role: 'user', text: trimmed }
    dispatch({ type: 'ADD_CHAT_MESSAGE', message: userMessage })
    setDraft('')

    const response = await run({
      message: trimmed,
      conversationId: state.chat.conversationId,
      context: {
        profileId: state.profile.result?.profileId,
        goalId: state.goal.result?.goalId,
        selectedPlanName: selectedPlan?.planName,
      },
    })

    if (!response) {
      dispatch({
        type: 'ADD_CHAT_MESSAGE',
        message: { id: newMessageId(), role: 'error', text: "Sorry, I couldn't get a response. Please try again." },
      })
      return
    }

    if (response.conversationId) {
      dispatch({ type: 'SET_CHAT_CONVERSATION_ID', conversationId: response.conversationId })
    }
    dispatch({
      type: 'ADD_CHAT_MESSAGE',
      message: { id: newMessageId(), role: 'assistant', text: response.reply || "I don't have a response for that yet." },
    })
  }

  function handleSubmit(e) {
    e.preventDefault()
    sendMessage(draft)
  }

  function handleClear() {
    dispatch({ type: 'SET_CHAT_MESSAGES', messages: [] })
    dispatch({ type: 'SET_CHAT_CONVERSATION_ID', conversationId: null })
  }

  return (
    <div>
      <div className="page-header">
        <h1>AI Financial Assistant</h1>
        <p>Ask questions about your plans. Answers are generated by the backend&rsquo;s GenAI layer, not this app.</p>
      </div>

      {selectedPlan ? (
        <div className="alert alert-success">
          <span aria-hidden="true">✓</span>
          <div className="flex-between" style={{ width: '100%' }}>
            <span>
              <strong>Plan saved:</strong> {selectedPlan.planName} <RiskBadge category={selectedPlan.riskLevel} />
            </span>
            <button
              type="button"
              className="btn btn-ghost btn-sm"
              onClick={() => dispatch({ type: 'GO_TO_STEP', step: 'plans' })}
            >
              Change plan
            </button>
          </div>
        </div>
      ) : (
        <div className="alert alert-warning">
          No plan selected yet. You can still chat, but select a plan for more grounded answers and to try What-If.
        </div>
      )}

      <DisclaimerBanner compact />

      <div className="chat-window mt-4">
        <div className="chat-messages" ref={scrollRef}>
          {messages.length === 0 && (
            <p className="text-faint">Ask about your plan&rsquo;s allocation, risk, or projected outcomes to get started.</p>
          )}
          {messages.map((message) => (
            <div key={message.id}>
              <div
                className={`chat-bubble ${
                  message.role === 'user'
                    ? 'chat-bubble--user'
                    : message.role === 'error'
                      ? 'chat-bubble--error'
                      : 'chat-bubble--assistant'
                }`}
              >
                {message.text}
              </div>
            </div>
          ))}
          {loading && (
            <div className="typing-indicator" aria-label="Assistant is typing">
              <span />
              <span />
              <span />
            </div>
          )}
        </div>

        <form className="chat-input-row" onSubmit={handleSubmit}>
          <textarea
            rows={1}
            placeholder="Ask a question about your financial plan..."
            value={draft}
            onChange={(e) => setDraft(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === 'Enter' && !e.shiftKey) {
                e.preventDefault()
                sendMessage(draft)
              }
            }}
          />
          <button type="submit" className="btn btn-primary" disabled={loading || !draft.trim()}>
            Send
          </button>
        </form>
      </div>

      <div className="flex-between mt-3">
        <div className="suggested-questions">
          {SUGGESTED_QUESTIONS.map((q) => (
            <button key={q} type="button" className="suggested-question-chip" onClick={() => sendMessage(q)}>
              {q}
            </button>
          ))}
        </div>
        {messages.length > 0 && (
          <button type="button" className="btn btn-ghost btn-sm" onClick={handleClear}>
            Clear conversation
          </button>
        )}
      </div>

      {error && (
        <div className="alert alert-error mt-3" role="alert">
          {error.message || 'Something went wrong reaching the assistant.'}
        </div>
      )}

      <WhatIfPanel />
    </div>
  )
}
